var gameDataProvinces = [
    'Adriatic Sea',
    'Aegean Sea',
    'Albania',
    'Ankara',
    'Apulia',
    'Armenia',
    'Baltic Sea',
    'Barents Sea',
    'Belgium',
    'Berlin',
    'Black Sea',
    'Bohemia',
    'Brest',
    'Budapest',
    'Bulgaria',
    'Burgundy',
    'Clyde',
    'Constantinople',
    'Denmark',
    'Eastern Mediterranean',
    'Edinburgh',
    'English Channel',
    'Finland',
    'Galicia',
    'Gascony',
    'Greece',
    'Gulf of Bothnia',
    'Gulf of Lyon',
    'Helgoland Bight',
    'Holland',
    'Ionian Sea',
    'Irish Sea',
    'Kiel',
    'Liverpool',
    'Livonia',
    'London',
    'Marseilles',
    'Mid-Atlantic Ocean',
    'Moscow',
    'Munich',
    'Naples',
    'North Africa',
    'North Atlantic Ocean',
    'North Sea',
    'Norway',
    'Norwegian Sea',
    'Paris',
    'Picardy',
    'Piedmont',
    'Portugal',
    'Prussia',
    'Rome',
    'Ruhr',
    'Rumania',
    'Serbia',
    'Sevastopol',
    'Silesia',
    'Skagerrak',
    'Smyrna',
    'Spain',
    'St Petersburg',
    'Sweden',
    'Switzerland',
    'Syria',
    'Trieste',
    'Tunis',
    'Tuscany',
    'Tyrolia',
    'Tyrrhenian Sea',
    'Ukraine',
    'Venice',
    'Vienna',
    'Wales',
    'Warsaw',
    'Western Mediterranean',
    'Yorkshire'
];